services:
  rabbitmq:
    image: rabbitmq:4.2.0-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hospital-network

  schedule-db:
    image: mysql:8.0
    container_name: schedule-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_schedule_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - hospital-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  clinic-db:
    image: mysql:8.0
    container_name: clinic-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_clinic_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - hospital-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  procedures-db:
    image: mysql:8.0
    container_name: procedures-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_procedures_data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - hospital-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_procedures_data:
  mysql_clinic_data:
  mysql_schedule_data:
  rabbitmq_data:

networks:
  hospital-network:
    driver: bridge