services:
  rabbitmq:
    image: rabbitmq:4.2.0-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hospital-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  schedule-db:
    image: mysql:8.0
    container_name: schedule-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_schedule_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - hospital-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

  clinic-db:
    image: mysql:8.0
    container_name: clinic-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_clinic_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - hospital-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

  lab-db:
    image: mysql:8.0
    container_name: lab-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_lab_data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - hospital-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak-db:
    image: mysql:8.0
    container_name: keycloak-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    volumes:
      - mysql_keycloak_data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - hospital-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-db:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_URL: http://localhost:8180
      KC_HOSTNAME_ADMIN_URL: http://localhost:8180
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8180:8080"
    networks:
      - hospital-network
    depends_on:
      keycloak-db:
        condition: service_healthy

  schedule:
    build:
      context: ./schedule
      dockerfile: Dockerfile
    container_name: schedule-service
    environment:
      SERVER_PORT: 8083
      DATASOURCE_URL: jdbc:mysql://schedule-db:3306/schedule_db?createDatabaseIfNotExist=true
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: root
      KEYCLOAK_ISSUER_URI: http://localhost:8180/realms/hospital
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/hospital/protocol/openid-connect/certs
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/hospital/protocol/openid-connect/token
      SCHEDULE_CLIENT_SECRET: XlRQC5MaUMHXpFgAz0Mc6wA0IX9x5Hzr
      CLINIC_URL: http://clinic:8081
      LAB_URL: http://lab:8082
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "8083:8083"
    networks:
      - hospital-network
    depends_on:
      schedule-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  clinic:
    build:
      context: ./clinic
      dockerfile: Dockerfile
    container_name: clinic-service
    environment:
      SERVER_PORT: 8081
      DATASOURCE_URL: jdbc:mysql://clinic-db:3306/clinic_db?createDatabaseIfNotExist=true
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: root
      KEYCLOAK_ISSUER_URI: http://localhost:8180/realms/hospital
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/hospital/protocol/openid-connect/certs
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/hospital/protocol/openid-connect/token
      CLINIC_CLIENT_SECRET: 78CTyi3vnLr1A5d9DNUht5JUANC9zC39
      LAB_URL: http://lab:8082
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8081"
    networks:
      - hospital-network
    depends_on:
      clinic-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  lab:
    build:
      context: ./procedures
      dockerfile: Dockerfile
    container_name: lab-service
    environment:
      SERVER_PORT: 8082
      DATASOURCE_URL: jdbc:mysql://lab-db:3306/lab_db?createDatabaseIfNotExist=true
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: root
      KEYCLOAK_ISSUER_URI: http://localhost:8180/realms/hospital
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/hospital/protocol/openid-connect/certs
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/hospital/protocol/openid-connect/token
      LAB_CLIENT_SECRET: IDlJM9G8b8pz5WTkVUylXhNPIqp2w80f
    ports:
      - "8082:8082"
    networks:
      - hospital-network
    depends_on:
      lab-db:
        condition: service_healthy

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    environment:
      SERVER_PORT: 8080
      SCHEDULE_SERVICE_URL: http://schedule:8083
      CLINIC_SERVICE_URL: http://clinic:8081
      LAB_SERVICE_URL: http://lab:8082
      KEYCLOAK_ISSUER_URI: http://localhost:8180/realms/hospital
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/hospital/protocol/openid-connect/certs
    ports:
      - "8080:8080"
    networks:
      - hospital-network
    depends_on:
      schedule:
        condition: service_started
      clinic:
        condition: service_started
      lab:
        condition: service_started

volumes:
  mysql_lab_data:
  mysql_clinic_data:
  mysql_schedule_data:
  mysql_keycloak_data:
  rabbitmq_data:

networks:
  hospital-network:
    driver: bridge