server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/hospital}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/hospital/protocol/openid-connect/certs}

  cloud:
    gateway:
      routes:
        - id: schedule-service
          uri: ${SCHEDULE_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/schedule/**
          filters:
            - StripPrefix=2

        - id: clinic-service
          uri: ${CLINIC_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/clinic/**
          filters:
            - StripPrefix=2

        - id: lab-service
          uri: ${LAB_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/lab/**
          filters:
            - StripPrefix=2