server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: schedule

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/hospital}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/hospital/protocol/openid-connect/certs}
      client:
        registration:
          schedule-service:
            client-id: schedule-service
            client-secret: ${SCHEDULE_CLIENT_SECRET:XlRQC5MaUMHXpFgAz0Mc6wA0IX9x5Hzr}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          schedule-service:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8180/realms/hospital/protocol/openid-connect/token}

  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3307/schedule_db?createDatabaseIfNotExist=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

services:
  clinic:
    url: ${CLINIC_URL:http://localhost:8081}
  lab:
    url: ${LAB_URL:http://localhost:8082}
